//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaptureResult
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CaptureResult()
        {
            this.CaptureResultProperties = new HashSet<CaptureResultProperty>();
            this.CaptureResultTuningValues = new HashSet<CaptureResultTuningValue>();
            this.FocalPoints = new HashSet<FocalPoint>();
            this.Images = new HashSet<Image>();
        }
    
        public long ID { get; set; }
        public long RegionID { get; set; }
        public int CaptureProfileVersionID { get; set; }
        public int ImageBatchID { get; set; }
        public Nullable<double> XCenter { get; set; }
        public Nullable<double> YCenter { get; set; }
        public Nullable<double> ZHeight { get; set; }
        public Nullable<double> XWidth { get; set; }
        public Nullable<double> YHeight { get; set; }
        public Nullable<long> AutoScoreImageID { get; set; }
        public string AutoScoreImageData { get; set; }
        public string AutoScoreImageDataVersion { get; set; }
        public string FrapDataPoint { get; set; }
    
        public virtual CaptureProfileVersion CaptureProfileVersion { get; set; }
        public virtual Image Image { get; set; }
        public virtual ImageBatch ImageBatch { get; set; }
        public virtual Region Region { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaptureResultProperty> CaptureResultProperties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaptureResultTuningValue> CaptureResultTuningValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FocalPoint> FocalPoints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Images { get; set; }
    }
}
