//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chart()
        {
            this.SearchTargetCharts = new HashSet<SearchTargetChart>();
            this.ChartRequiredFields = new HashSet<ChartRequiredField>();
            this.SearchCharts = new HashSet<SearchChart>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Query { get; set; }
        public string XAxis { get; set; }
        public string YAxis { get; set; }
        public string Series { get; set; }
        public string DefaultChartType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SearchTargetChart> SearchTargetCharts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChartRequiredField> ChartRequiredFields { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SearchChart> SearchCharts { get; set; }
    }
}
