//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Container
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Container()
        {
            this.ContainerDrops = new HashSet<ContainerDrop>();
            this.Experiments = new HashSet<Experiment>();
            this.ScreenLots = new HashSet<ScreenLot>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int NumRows { get; set; }
        public int NumColumns { get; set; }
        public double DefaultWellVolume { get; set; }
        public double DefaultAdditiveVolume { get; set; }
        public double MaxWellVolume { get; set; }
        public int MaxNumDrops { get; set; }
        public double DefaultDropVolume { get; set; }
        public double MaxDropVolume { get; set; }
        public int Type { get; set; }
        public bool Enable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContainerDrop> ContainerDrops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Experiment> Experiments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScreenLot> ScreenLots { get; set; }
    }
}
