//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GridIngredient
    {
        public int ID { get; set; }
        public int GridID { get; set; }
        public int IngredientIngredientTypeID { get; set; }
        public int IngredientStockID { get; set; }
        public Nullable<int> HighPHIngredientStockID { get; set; }
        public double StartConcentration { get; set; }
        public double StopConcentration { get; set; }
        public int ConcentrationVaryAlong { get; set; }
        public Nullable<double> StartpH { get; set; }
        public Nullable<double> StoppH { get; set; }
        public Nullable<int> pHVaryAlong { get; set; }
    
        public virtual Grid Grid { get; set; }
        public virtual GridVaryAlong GridVaryAlong { get; set; }
        public virtual GridVaryAlong GridVaryAlong1 { get; set; }
        public virtual IngredientIngredientType IngredientIngredientType { get; set; }
        public virtual IngredientStock IngredientStock { get; set; }
        public virtual IngredientStock IngredientStock1 { get; set; }
    }
}
