//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagingScheduleEntryCaptureProfile
    {
        public long ID { get; set; }
        public int ImagingScheduleEntryID { get; set; }
        public int CaptureProfileID { get; set; }
    
        public virtual CaptureProfile CaptureProfile { get; set; }
        public virtual ImagingScheduleEntry ImagingScheduleEntry { get; set; }
    }
}
