//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageBatchAutoScoreThreshold
    {
        public int ID { get; set; }
        public int ImageBatchID { get; set; }
        public int AutoScoreImageTypeID { get; set; }
        public double Value { get; set; }
    
        public virtual ImageBatch ImageBatch { get; set; }
    }
}
