//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagingScheduleEntry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ImagingScheduleEntry()
        {
            this.ImagingScheduleEntryCaptureProfiles = new HashSet<ImagingScheduleEntryCaptureProfile>();
            this.ImagingTasks = new HashSet<ImagingTask>();
        }
    
        public int ID { get; set; }
        public int ImagingScheduleID { get; set; }
        public int Days { get; set; }
        public int Hours { get; set; }
        public bool Notify { get; set; }
        public int Priority { get; set; }
    
        public virtual ImagingSchedule ImagingSchedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImagingScheduleEntryCaptureProfile> ImagingScheduleEntryCaptureProfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImagingTask> ImagingTasks { get; set; }
    }
}
