//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ingredient()
        {
            this.BufferDataPoints = new HashSet<BufferDataPoint>();
            this.CASNumbers = new HashSet<CASNumber>();
            this.IngredientAlias = new HashSet<IngredientAlia>();
            this.IngredientIngredientTypes = new HashSet<IngredientIngredientType>();
            this.IngredientStocks = new HashSet<IngredientStock>();
            this.RandomLayerExcludeLists = new HashSet<RandomLayerExcludeList>();
            this.RandomLayerExcludeLists1 = new HashSet<RandomLayerExcludeList>();
        }
    
        public int ID { get; set; }
        public string LongName { get; set; }
        public string ShortName { get; set; }
        public int MaxStockNumber { get; set; }
        public Nullable<int> DefaultNonBufferIngredientStockID { get; set; }
        public Nullable<int> DefaultBufferIngredientStockID { get; set; }
        public Nullable<int> BufferCalculationTypeID { get; set; }
        public Nullable<double> pKa { get; set; }
        public Nullable<int> ExportIngredientAliasID { get; set; }
    
        public virtual BufferCalculationType BufferCalculationType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BufferDataPoint> BufferDataPoints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CASNumber> CASNumbers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngredientAlia> IngredientAlias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngredientIngredientType> IngredientIngredientTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngredientStock> IngredientStocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RandomLayerExcludeList> RandomLayerExcludeLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RandomLayerExcludeList> RandomLayerExcludeLists1 { get; set; }
    }
}
