//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngredientStock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IngredientStock()
        {
            this.ConditionIngredients = new HashSet<ConditionIngredient>();
            this.ConditionIngredients1 = new HashSet<ConditionIngredient>();
            this.FavoriteIngredientStocks = new HashSet<FavoriteIngredientStock>();
            this.GridIngredients = new HashSet<GridIngredient>();
            this.GridIngredients1 = new HashSet<GridIngredient>();
            this.ProteinFormulationStandardIngredients = new HashSet<ProteinFormulationStandardIngredient>();
            this.ProteinFormulationStandardIngredients1 = new HashSet<ProteinFormulationStandardIngredient>();
            this.RackIngredients = new HashSet<RackIngredient>();
            this.RandomLayerGroupIngredients = new HashSet<RandomLayerGroupIngredient>();
            this.RandomLayerGroupIngredients1 = new HashSet<RandomLayerGroupIngredient>();
            this.WellDropLayerIngredients = new HashSet<WellDropLayerIngredient>();
            this.WellDropLayerIngredients1 = new HashSet<WellDropLayerIngredient>();
            this.WellLayerIngredients = new HashSet<WellLayerIngredient>();
            this.WellLayerIngredients1 = new HashSet<WellLayerIngredient>();
        }
    
        public int ID { get; set; }
        public int IngredientID { get; set; }
        public int StockNumber { get; set; }
        public double StockConcentration { get; set; }
        public double LowConcentration { get; set; }
        public double HighConcentration { get; set; }
        public string ConcentrationUnits { get; set; }
        public Nullable<double> StockPH { get; set; }
        public bool IsBuffer { get; set; }
        public bool IsPrepared { get; set; }
        public int LiquidClassID { get; set; }
        public bool LabelPrinted { get; set; }
        public int DispenseOrder { get; set; }
        public Nullable<int> VendorID { get; set; }
        public string VendorPartNumber { get; set; }
        public string Comments { get; set; }
        public string StockLocation { get; set; }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConditionIngredient> ConditionIngredients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConditionIngredient> ConditionIngredients1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FavoriteIngredientStock> FavoriteIngredientStocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GridIngredient> GridIngredients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GridIngredient> GridIngredients1 { get; set; }
        public virtual Ingredient Ingredient { get; set; }
        public virtual LiquidClass LiquidClass { get; set; }
        public virtual Vendor Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProteinFormulationStandardIngredient> ProteinFormulationStandardIngredients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProteinFormulationStandardIngredient> ProteinFormulationStandardIngredients1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RackIngredient> RackIngredients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RandomLayerGroupIngredient> RandomLayerGroupIngredients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RandomLayerGroupIngredient> RandomLayerGroupIngredients1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WellDropLayerIngredient> WellDropLayerIngredients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WellDropLayerIngredient> WellDropLayerIngredients1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WellLayerIngredient> WellLayerIngredients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WellLayerIngredient> WellLayerIngredients1 { get; set; }
    }
}
