//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlateEvent
    {
        public long ID { get; set; }
        public long PlateID { get; set; }
        public int PlateEventTypeID { get; set; }
        public System.DateTime EventDate { get; set; }
    
        public virtual Plate Plate { get; set; }
        public virtual PlateEventType PlateEventType { get; set; }
    }
}
