//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public string ForeignKeyTable { get; set; }
        public Nullable<int> ForeignKeyID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> GroupID { get; set; }
    }
}
