//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProteinLayerProteinFormulation
    {
        public int ID { get; set; }
        public int ProteinLayerID { get; set; }
        public int ProteinFormulationID { get; set; }
        public double StartWellDropVolume { get; set; }
        public double StopWellDropVolume { get; set; }
        public int WellDropVolumeVaryAlong { get; set; }
        public double StartProteinDropVolume { get; set; }
        public double StopProteinDropVolume { get; set; }
        public int ProteinDropVolumeVaryAlong { get; set; }
    
        public virtual ProteinFormulation ProteinFormulation { get; set; }
        public virtual ProteinLayer ProteinLayer { get; set; }
    }
}
