//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProteinLayer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProteinLayer()
        {
            this.ProteinLayerProteinFormulations = new HashSet<ProteinLayerProteinFormulation>();
        }
    
        public int ID { get; set; }
        public int ExperimentID { get; set; }
        public long LayerID { get; set; }
    
        public virtual Layer Layer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProteinLayerProteinFormulation> ProteinLayerProteinFormulations { get; set; }
    }
}
