//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RandomLayer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RandomLayer()
        {
            this.RandomLayerExcludeLists = new HashSet<RandomLayerExcludeList>();
            this.RandomLayerIngredientGroups = new HashSet<RandomLayerIngredientGroup>();
        }
    
        public int ID { get; set; }
        public long LayerID { get; set; }
        public int ExperimentID { get; set; }
        public int GridSteps { get; set; }
        public double WellVolume { get; set; }
    
        public virtual Experiment Experiment { get; set; }
        public virtual Layer Layer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RandomLayerExcludeList> RandomLayerExcludeLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RandomLayerIngredientGroup> RandomLayerIngredientGroups { get; set; }
    }
}
