//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionScribblePoint
    {
        public long ID { get; set; }
        public int RegionScribbleID { get; set; }
        public int PointIndex { get; set; }
        public double XOffset { get; set; }
        public double YOffset { get; set; }
    
        public virtual RegionScribble RegionScribble { get; set; }
    }
}
