//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScreenLot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScreenLot()
        {
            this.ScreenLayers = new HashSet<ScreenLayer>();
            this.ScreenLotPlates = new HashSet<ScreenLotPlate>();
        }
    
        public int ID { get; set; }
        public int ExperimentID { get; set; }
        public int ContainerID { get; set; }
        public int TreeNodeID { get; set; }
        public int LotNumber { get; set; }
        public double DispenseVolume { get; set; }
        public double CurrentVolume { get; set; }
        public string Comment { get; set; }
        public bool InitialLot { get; set; }
    
        public virtual Container Container { get; set; }
        public virtual Experiment Experiment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScreenLayer> ScreenLayers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScreenLotPlate> ScreenLotPlates { get; set; }
    }
}
