//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchDisplayField
    {
        public int ID { get; set; }
        public int SearchFieldID { get; set; }
        public int SearchID { get; set; }
        public int DisplayOrder { get; set; }
        public string ColumnHeader { get; set; }
        public int Status { get; set; }
    
        public virtual Search Search { get; set; }
        public virtual SearchField SearchField { get; set; }
    }
}
