//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchTarget
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SearchTarget()
        {
            this.Searches = new HashSet<Search>();
            this.Searches1 = new HashSet<Search>();
            this.SearchFields = new HashSet<SearchField>();
            this.SearchTargetCharts = new HashSet<SearchTargetChart>();
            this.SearchTargetFields = new HashSet<SearchTargetField>();
            this.SearchTargetFields1 = new HashSet<SearchTargetField>();
            this.SearchTargetRelations = new HashSet<SearchTargetRelation>();
            this.SearchTargetRelations1 = new HashSet<SearchTargetRelation>();
        }
    
        public int ID { get; set; }
        public string TargetName { get; set; }
        public string TableName { get; set; }
        public string TableHints { get; set; }
        public string Joins { get; set; }
        public string TreeNodeField { get; set; }
        public bool Visible { get; set; }
        public Nullable<int> DefaultSortColumn { get; set; }
        public bool NewSearchTarget { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Search> Searches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Search> Searches1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SearchField> SearchFields { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SearchTargetChart> SearchTargetCharts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SearchTargetField> SearchTargetFields { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SearchTargetField> SearchTargetFields1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SearchTargetRelation> SearchTargetRelations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SearchTargetRelation> SearchTargetRelations1 { get; set; }
    }
}
