//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchResultField
    {
        public int ID { get; set; }
        public Nullable<int> SearchFieldID { get; set; }
        public Nullable<int> SearchID { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public string ColumnHeader { get; set; }
    
        public virtual Search Search { get; set; }
        public virtual Search Search1 { get; set; }
        public virtual SearchField SearchField { get; set; }
        public virtual SearchField SearchField1 { get; set; }
    }
}
