//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreeNodeAccessRight
    {
        public int ID { get; set; }
        public int AccessRightID { get; set; }
        public int TreeNodeID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> GroupID { get; set; }
    
        public virtual AccessRight AccessRight { get; set; }
        public virtual Group Group { get; set; }
        public virtual TreeNode TreeNode { get; set; }
        public virtual User User { get; set; }
    }
}
