//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Well
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Well()
        {
            this.WellDrops = new HashSet<WellDrop>();
            this.WellLayers = new HashSet<WellLayer>();
        }
    
        public long ID { get; set; }
        public long PlateID { get; set; }
        public int WellNumber { get; set; }
        public string RowLetter { get; set; }
        public int ColumnNumber { get; set; }
        public Nullable<double> Volume { get; set; }
        public Nullable<double> WaterVolume { get; set; }
        public Nullable<double> CurrentVolume { get; set; }
    
        public virtual Plate Plate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WellDrop> WellDrops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WellLayer> WellLayers { get; set; }
    }
}
