//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RockMakerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BufferDataPoint
    {
        public int ID { get; set; }
        public int IngredientID { get; set; }
        public double pH { get; set; }
        public double Ratio { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
    }
}
