//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RockMakerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaptureProperty
    {
        public long ID { get; set; }
        public int CaptureProfileVersionID { get; set; }
        public int RobotID { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
    
        public virtual CaptureProfileVersion CaptureProfileVersion { get; set; }
    }
}
