//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RockMakerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExperimentPlate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExperimentPlate()
        {
            this.CaptureProfiles = new HashSet<CaptureProfile>();
            this.ImagingTasks = new HashSet<ImagingTask>();
        }
    
        public long ID { get; set; }
        public long PlateID { get; set; }
        public bool ImagingTasksEnabled { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> ImagesViewed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaptureProfile> CaptureProfiles { get; set; }
        public virtual Plate Plate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImagingTask> ImagingTasks { get; set; }
    }
}
