//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RockMakerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GridLayer
    {
        public long ID { get; set; }
        public int GridID { get; set; }
        public long LayerID { get; set; }
        public int SubGridNumber { get; set; }
    
        public virtual Grid Grid { get; set; }
        public virtual Layer Layer { get; set; }
    }
}
