//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RockMakerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageManagement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ImageManagement()
        {
            this.ImageManagementActions = new HashSet<ImageManagementAction>();
        }
    
        public int ID { get; set; }
        public int TreeNodeID { get; set; }
        public Nullable<int> ErrorBehaviour { get; set; }
    
        public virtual TreeNode TreeNode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageManagementAction> ImageManagementActions { get; set; }
    }
}
