//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RockMakerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagingTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ImagingTask()
        {
            this.ImageBatches = new HashSet<ImageBatch>();
            this.ImagingTaskCaptureProfiles = new HashSet<ImagingTaskCaptureProfile>();
            this.ImagingTaskWellDrops = new HashSet<ImagingTaskWellDrop>();
        }
    
        public int ID { get; set; }
        public long ExperimentPlateID { get; set; }
        public Nullable<int> ImagingScheduleEntryID { get; set; }
        public int State { get; set; }
        public System.DateTime DateToImage { get; set; }
        public Nullable<System.DateTime> DateImaged { get; set; }
        public bool ClearedFromToImage { get; set; }
        public bool ClearedFromToScore { get; set; }
        public Nullable<int> ExperimentPlateImagingScheduleEntryCalc { get; set; }
        public int Source { get; set; }
        public int Priority { get; set; }
    
        public virtual ExperimentPlate ExperimentPlate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageBatch> ImageBatches { get; set; }
        public virtual ImagingScheduleEntry ImagingScheduleEntry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImagingTaskCaptureProfile> ImagingTaskCaptureProfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImagingTaskWellDrop> ImagingTaskWellDrops { get; set; }
    }
}
