//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RockMakerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagingTaskCaptureProfile
    {
        public int ID { get; set; }
        public int ImagingTaskID { get; set; }
        public int CaptureProfileID { get; set; }
    
        public virtual CaptureProfile CaptureProfile { get; set; }
        public virtual ImagingTask ImagingTask { get; set; }
    }
}
