//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RockMakerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Image()
        {
            this.CaptureResults = new HashSet<CaptureResult>();
            this.ImageProperties = new HashSet<ImageProperty>();
        }
    
        public long ID { get; set; }
        public long CaptureResultID { get; set; }
        public int ImageStoreID { get; set; }
        public int ImageTypeID { get; set; }
        public int ImageTypeIndex { get; set; }
        public Nullable<double> PixelSize { get; set; }
        public Nullable<double> XCenterOffset { get; set; }
        public Nullable<double> YCenterOffset { get; set; }
        public Nullable<double> ZHeight { get; set; }
        public Nullable<int> FileSize { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaptureResult> CaptureResults { get; set; }
        public virtual CaptureResult CaptureResult { get; set; }
        public virtual ImageStore ImageStore { get; set; }
        public virtual ImageType ImageType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageProperty> ImageProperties { get; set; }
    }
}
