//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RockMakerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngredientIngredientType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IngredientIngredientType()
        {
            this.ConditionIngredients = new HashSet<ConditionIngredient>();
            this.FavoriteIngredientStocks = new HashSet<FavoriteIngredientStock>();
            this.GridIngredients = new HashSet<GridIngredient>();
            this.ProteinFormulationStandardIngredients = new HashSet<ProteinFormulationStandardIngredient>();
            this.RandomLayerGroupIngredients = new HashSet<RandomLayerGroupIngredient>();
            this.WellDropLayerIngredients = new HashSet<WellDropLayerIngredient>();
            this.WellLayerIngredients = new HashSet<WellLayerIngredient>();
        }
    
        public int ID { get; set; }
        public int IngredientID { get; set; }
        public int IngredientTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConditionIngredient> ConditionIngredients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FavoriteIngredientStock> FavoriteIngredientStocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GridIngredient> GridIngredients { get; set; }
        public virtual Ingredient Ingredient { get; set; }
        public virtual IngredientType IngredientType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProteinFormulationStandardIngredient> ProteinFormulationStandardIngredients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RandomLayerGroupIngredient> RandomLayerGroupIngredients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WellDropLayerIngredient> WellDropLayerIngredients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WellLayerIngredient> WellLayerIngredients { get; set; }
    }
}
