//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RockMakerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProteinFormulation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProteinFormulation()
        {
            this.ProteinFormulationAttachments = new HashSet<ProteinFormulationAttachment>();
            this.ProteinFormulationIngredients = new HashSet<ProteinFormulationIngredient>();
            this.ProteinFormulationStandardIngredients = new HashSet<ProteinFormulationStandardIngredient>();
            this.ProteinLayerProteinFormulations = new HashSet<ProteinLayerProteinFormulation>();
            this.WellDrops = new HashSet<WellDrop>();
        }
    
        public int ID { get; set; }
        public int TreeNodeID { get; set; }
        public string ProteinLotID { get; set; }
        public string Class { get; set; }
        public System.DateTime DatePrepared { get; set; }
        public Nullable<double> Volume { get; set; }
        public Nullable<double> StorageTemperature { get; set; }
        public string ExtinctionCoefficient { get; set; }
        public string NotebookPageNo { get; set; }
        public string Notes { get; set; }
        public int LiquidClassID { get; set; }
    
        public virtual LiquidClass LiquidClass { get; set; }
        public virtual LiquidClass LiquidClass1 { get; set; }
        public virtual TreeNode TreeNode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProteinFormulationAttachment> ProteinFormulationAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProteinFormulationIngredient> ProteinFormulationIngredients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProteinFormulationStandardIngredient> ProteinFormulationStandardIngredients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProteinLayerProteinFormulation> ProteinLayerProteinFormulations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WellDrop> WellDrops { get; set; }
    }
}
