//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RockMakerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RandomLayerGenerationList
    {
        public int ID { get; set; }
        public int RandomLayerID { get; set; }
        public int RandomLayerIngredientGroupID { get; set; }
        public double Probability { get; set; }
    
        public virtual RandomLayerIngredientGroup RandomLayerIngredientGroup { get; set; }
    }
}
