//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RockMakerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RandomLayerIngredientGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RandomLayerIngredientGroup()
        {
            this.RandomLayerGenerationLists = new HashSet<RandomLayerGenerationList>();
            this.RandomLayerGroupIngredients = new HashSet<RandomLayerGroupIngredient>();
        }
    
        public int ID { get; set; }
        public int RandomLayerID { get; set; }
        public string Name { get; set; }
    
        public virtual RandomLayer RandomLayer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RandomLayerGenerationList> RandomLayerGenerationLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RandomLayerGroupIngredient> RandomLayerGroupIngredients { get; set; }
    }
}
