//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RockMakerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionAnnotation
    {
        public int ID { get; set; }
        public long RegionID { get; set; }
        public int RegionAnnotationTypeID { get; set; }
        public bool Expanded { get; set; }
        public double X { get; set; }
        public double Y { get; set; }
        public double Width { get; set; }
        public double Height { get; set; }
        public string Font { get; set; }
        public string Text { get; set; }
    
        public virtual Region Region { get; set; }
        public virtual RegionAnnotationType RegionAnnotationType { get; set; }
    }
}
