//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RockMakerModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RockMakerEntities : DbContext
    {
        public RockMakerEntities()
            : base("name=RockMakerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccessRight> AccessRights { get; set; }
        public virtual DbSet<BufferCalculationType> BufferCalculationTypes { get; set; }
        public virtual DbSet<BufferDataPoint> BufferDataPoints { get; set; }
        public virtual DbSet<CaptureProfile> CaptureProfiles { get; set; }
        public virtual DbSet<CaptureProfileTuningValue> CaptureProfileTuningValues { get; set; }
        public virtual DbSet<CaptureProfileVersion> CaptureProfileVersions { get; set; }
        public virtual DbSet<CaptureProperty> CaptureProperties { get; set; }
        public virtual DbSet<CaptureResult> CaptureResults { get; set; }
        public virtual DbSet<CaptureResultProperty> CaptureResultProperties { get; set; }
        public virtual DbSet<CaptureResultTuningValue> CaptureResultTuningValues { get; set; }
        public virtual DbSet<CASNumber> CASNumbers { get; set; }
        public virtual DbSet<Chart> Charts { get; set; }
        public virtual DbSet<ChartRequiredField> ChartRequiredFields { get; set; }
        public virtual DbSet<Condition> Conditions { get; set; }
        public virtual DbSet<ConditionIngredient> ConditionIngredients { get; set; }
        public virtual DbSet<ConditionListLayer> ConditionListLayers { get; set; }
        public virtual DbSet<ContainerDrop> ContainerDrops { get; set; }
        public virtual DbSet<Container> Containers { get; set; }
        public virtual DbSet<DatabaseProperty> DatabaseProperties { get; set; }
        public virtual DbSet<Deck> Decks { get; set; }
        public virtual DbSet<DispenseQueue> DispenseQueues { get; set; }
        public virtual DbSet<DispensingRobot> DispensingRobots { get; set; }
        public virtual DbSet<DispensingRobotType> DispensingRobotTypes { get; set; }
        public virtual DbSet<DriverProperty> DriverProperties { get; set; }
        public virtual DbSet<Experiment> Experiments { get; set; }
        public virtual DbSet<ExperimentCaptureProfileTuningValue> ExperimentCaptureProfileTuningValues { get; set; }
        public virtual DbSet<ExperimentPlate> ExperimentPlates { get; set; }
        public virtual DbSet<ExperimentPlateEvent> ExperimentPlateEvents { get; set; }
        public virtual DbSet<FavoriteIngredientStock> FavoriteIngredientStocks { get; set; }
        public virtual DbSet<Filter> Filters { get; set; }
        public virtual DbSet<FilterValue> FilterValues { get; set; }
        public virtual DbSet<FocalPoint> FocalPoints { get; set; }
        public virtual DbSet<Grid> Grids { get; set; }
        public virtual DbSet<GridIngredient> GridIngredients { get; set; }
        public virtual DbSet<GridLayer> GridLayers { get; set; }
        public virtual DbSet<GridVaryAlong> GridVaryAlongs { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<GroupUser> GroupUsers { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<ImageBatch> ImageBatches { get; set; }
        public virtual DbSet<ImageBatchAutoScoreThreshold> ImageBatchAutoScoreThresholds { get; set; }
        public virtual DbSet<ImageBatchWellDropScore> ImageBatchWellDropScores { get; set; }
        public virtual DbSet<ImageManagement> ImageManagements { get; set; }
        public virtual DbSet<ImageManagementAction> ImageManagementActions { get; set; }
        public virtual DbSet<ImageProperty> ImageProperties { get; set; }
        public virtual DbSet<Imager> Imagers { get; set; }
        public virtual DbSet<ImagerGroup> ImagerGroups { get; set; }
        public virtual DbSet<ImageStore> ImageStores { get; set; }
        public virtual DbSet<ImageStoreLayout> ImageStoreLayouts { get; set; }
        public virtual DbSet<ImageType> ImageTypes { get; set; }
        public virtual DbSet<ImagingSchedule> ImagingSchedules { get; set; }
        public virtual DbSet<ImagingScheduleEntry> ImagingScheduleEntries { get; set; }
        public virtual DbSet<ImagingScheduleEntryCaptureProfile> ImagingScheduleEntryCaptureProfiles { get; set; }
        public virtual DbSet<ImagingTask> ImagingTasks { get; set; }
        public virtual DbSet<ImagingTaskCaptureProfile> ImagingTaskCaptureProfiles { get; set; }
        public virtual DbSet<ImagingTaskWellDrop> ImagingTaskWellDrops { get; set; }
        public virtual DbSet<IncubationTemp> IncubationTemps { get; set; }
        public virtual DbSet<Ingredient> Ingredients { get; set; }
        public virtual DbSet<IngredientAlia> IngredientAlias { get; set; }
        public virtual DbSet<IngredientIngredientType> IngredientIngredientTypes { get; set; }
        public virtual DbSet<IngredientStock> IngredientStocks { get; set; }
        public virtual DbSet<IngredientType> IngredientTypes { get; set; }
        public virtual DbSet<IngredientTypeColor> IngredientTypeColors { get; set; }
        public virtual DbSet<Layer> Layers { get; set; }
        public virtual DbSet<LidStorage> LidStorages { get; set; }
        public virtual DbSet<LidStorageType> LidStorageTypes { get; set; }
        public virtual DbSet<LiquidClass> LiquidClasses { get; set; }
        public virtual DbSet<MicrofluidicsExperiment> MicrofluidicsExperiments { get; set; }
        public virtual DbSet<MicrofluidicsImageBatchWellDropRank> MicrofluidicsImageBatchWellDropRanks { get; set; }
        public virtual DbSet<NotificationType> NotificationTypes { get; set; }
        public virtual DbSet<Plate> Plates { get; set; }
        public virtual DbSet<PlateEventType> PlateEventTypes { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Property> Properties { get; set; }
        public virtual DbSet<PropertyListType> PropertyListTypes { get; set; }
        public virtual DbSet<PropertyListValue> PropertyListValues { get; set; }
        public virtual DbSet<ProteinFormulation> ProteinFormulations { get; set; }
        public virtual DbSet<ProteinFormulationAttachment> ProteinFormulationAttachments { get; set; }
        public virtual DbSet<ProteinFormulationIngredient> ProteinFormulationIngredients { get; set; }
        public virtual DbSet<ProteinFormulationIngredientType> ProteinFormulationIngredientTypes { get; set; }
        public virtual DbSet<ProteinFormulationStandardIngredient> ProteinFormulationStandardIngredients { get; set; }
        public virtual DbSet<ProteinLayer> ProteinLayers { get; set; }
        public virtual DbSet<ProteinLayerProteinFormulation> ProteinLayerProteinFormulations { get; set; }
        public virtual DbSet<Rack> Racks { get; set; }
        public virtual DbSet<RackIngredient> RackIngredients { get; set; }
        public virtual DbSet<RackType> RackTypes { get; set; }
        public virtual DbSet<RandomLayer> RandomLayers { get; set; }
        public virtual DbSet<RandomLayerExcludeList> RandomLayerExcludeLists { get; set; }
        public virtual DbSet<RandomLayerGenerationList> RandomLayerGenerationLists { get; set; }
        public virtual DbSet<RandomLayerGroupIngredient> RandomLayerGroupIngredients { get; set; }
        public virtual DbSet<RandomLayerIngredientGroup> RandomLayerIngredientGroups { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<RegionAnnotation> RegionAnnotations { get; set; }
        public virtual DbSet<RegionAnnotationType> RegionAnnotationTypes { get; set; }
        public virtual DbSet<RegionCaptureProfile> RegionCaptureProfiles { get; set; }
        public virtual DbSet<RegionProperty> RegionProperties { get; set; }
        public virtual DbSet<RegionRuler> RegionRulers { get; set; }
        public virtual DbSet<RegionScribble> RegionScribbles { get; set; }
        public virtual DbSet<RegionScribblePoint> RegionScribblePoints { get; set; }
        public virtual DbSet<RegionType> RegionTypes { get; set; }
        public virtual DbSet<ScreenExperiment> ScreenExperiments { get; set; }
        public virtual DbSet<ScreenLayer> ScreenLayers { get; set; }
        public virtual DbSet<ScreenLot> ScreenLots { get; set; }
        public virtual DbSet<ScreenLotPlate> ScreenLotPlates { get; set; }
        public virtual DbSet<Search> Searches { get; set; }
        public virtual DbSet<SearchChart> SearchCharts { get; set; }
        public virtual DbSet<SearchConstraint> SearchConstraints { get; set; }
        public virtual DbSet<SearchConstraintTreeNode> SearchConstraintTreeNodes { get; set; }
        public virtual DbSet<SearchDisplayField> SearchDisplayFields { get; set; }
        public virtual DbSet<SearchField> SearchFields { get; set; }
        public virtual DbSet<SearchPath> SearchPaths { get; set; }
        public virtual DbSet<SearchResultField> SearchResultFields { get; set; }
        public virtual DbSet<SearchTarget> SearchTargets { get; set; }
        public virtual DbSet<SearchTargetField> SearchTargetFields { get; set; }
        public virtual DbSet<SearchTargetRelation> SearchTargetRelations { get; set; }
        public virtual DbSet<SetupTemp> SetupTemps { get; set; }
        public virtual DbSet<TreeNode> TreeNodes { get; set; }
        public virtual DbSet<TreeNodeAccessRight> TreeNodeAccessRights { get; set; }
        public virtual DbSet<TreeNodeFile> TreeNodeFiles { get; set; }
        public virtual DbSet<UserRecentDocument> UserRecentDocuments { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<Well> Wells { get; set; }
        public virtual DbSet<WellDrop> WellDrops { get; set; }
        public virtual DbSet<WellDropLayer> WellDropLayers { get; set; }
        public virtual DbSet<WellDropLayerIngredient> WellDropLayerIngredients { get; set; }
        public virtual DbSet<WellDropScore> WellDropScores { get; set; }
        public virtual DbSet<WellDropScoreGroup> WellDropScoreGroups { get; set; }
        public virtual DbSet<WellLayer> WellLayers { get; set; }
        public virtual DbSet<WellLayerIngredient> WellLayerIngredients { get; set; }
        public virtual DbSet<PlateEvent> PlateEvents { get; set; }
        public virtual DbSet<SearchTargetChart> SearchTargetCharts { get; set; }
    }
}
