//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RockMakerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchPath
    {
        public int ID { get; set; }
        public Nullable<int> SearchID { get; set; }
        public Nullable<int> TreeNodeID { get; set; }
    
        public virtual Search Search { get; set; }
        public virtual Search Search1 { get; set; }
        public virtual TreeNode TreeNode { get; set; }
        public virtual TreeNode TreeNode1 { get; set; }
    }
}
