//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RockMakerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchTargetRelation
    {
        public int SearchTargetParentID { get; set; }
        public int SearchTargetChildID { get; set; }
        public string ParentField { get; set; }
        public string ChildField { get; set; }
    
        public virtual SearchTarget SearchTarget { get; set; }
        public virtual SearchTarget SearchTarget1 { get; set; }
    }
}
