//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RockMakerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreeNodeFile
    {
        public int ID { get; set; }
        public int TreeNodeID { get; set; }
        public byte[] Data { get; set; }
        public System.DateTime CreationTime { get; set; }
    
        public virtual TreeNode TreeNode { get; set; }
    }
}
