//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RockMakerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WellDropLayerIngredient
    {
        public long ID { get; set; }
        public long WellDropLayerID { get; set; }
        public int IngredientIngredientTypeID { get; set; }
        public int IngredientStockID { get; set; }
        public Nullable<int> HighPHIngredientStockID { get; set; }
        public double Concentration { get; set; }
        public double PreMixedConcentration { get; set; }
        public double Volume { get; set; }
        public Nullable<double> PH { get; set; }
        public Nullable<double> LowPHVolume { get; set; }
        public Nullable<double> HighPHVolume { get; set; }
        public string Source { get; set; }
        public string HighPHSource { get; set; }
    
        public virtual IngredientIngredientType IngredientIngredientType { get; set; }
        public virtual IngredientStock IngredientStock { get; set; }
        public virtual IngredientStock IngredientStock1 { get; set; }
        public virtual WellDropLayer WellDropLayer { get; set; }
    }
}
