//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RockMakerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WellDropScoreGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WellDropScoreGroup()
        {
            this.WellDropScores = new HashSet<WellDropScore>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public bool IsAutoScore { get; set; }
        public string Unit { get; set; }
        public Nullable<int> AutoScoreType { get; set; }
        public Nullable<bool> Inherits { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WellDropScore> WellDropScores { get; set; }
    }
}
