//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RockMakerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WellDropScore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WellDropScore()
        {
            this.ImageBatchWellDropScores = new HashSet<ImageBatchWellDropScore>();
        }
    
        public int ID { get; set; }
        public int WellDropScoreGroupID { get; set; }
        public string Name { get; set; }
        public string HotKey { get; set; }
        public int OrderNumber { get; set; }
        public int Color { get; set; }
        public double Value { get; set; }
        public bool Hit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageBatchWellDropScore> ImageBatchWellDropScores { get; set; }
        public virtual WellDropScoreGroup WellDropScoreGroup { get; set; }
    }
}
